export const skills = [
    "python",
    "HTML",
    "CSS",
    "JavaScript (JS)",
    "React",
    "Bootstrap",
    "Jupyter Notebooks",
    "Node.JS",
    "postgreSQL",
    "Workshop Facilitation",
]

export const cert_data = [
    // {
    //     active: true,
    //     cert_name: "",
    //     subtitle: "",
    //     sub_url: "",
    //     img: "",
    //     img_alt: "",
    //     company: "",
    //     desc: "",
    //     site: "",
    //     youtube: "",
    //     // skills: [1, 2, 3, 4, 5]
    // },
    {
        active: true,
        cert_name: "Strategic Execution Professional (SEP)",
        subtitle: "Duke CE",
        sub_url: "https://www.dukece.com/offerings/ready-to-learn/adaptive-strategic-execution-program/",
        // img: "https://media.licdn.com/dms/image/v2/D5622AQGQoGsdJFTvqQ/feedshare-shrink_800/feedshare-shrink_800/0/1731124342985?e=1744848000&v=beta&t=DGgLl0Q2y-c5dzHgZU4uDREeeOZqvNbXQTv7PXBZeKI",
        img: "/IMGs/certs/AdaptiveStrategicExecutionProgram.png",
        img_alt: "Letter of completion for SEP from Duke CE",
        company: "Duke CE",
        desc: "Adaptive leadership is a skills framework at the forefront of the latest thinking in leadership & development. Enables individuals and organizations to adapt & thrive in the face of complicated situations.",
        site: "https://www.linkedin.com/feed/update/urn:li:activity:7260861763020075009/",
        youtube: "",
        // skills: [1, 2, 3, 4, 5]
    },
    {
        active: true,
        cert_name: "Design Sprint Facilitation",
        subtitle: "Workshopping & Software Design",
        sub_url: "https://www.thesprintbook.com/the-design-sprint",
        img: "https://imgs.search.brave.com/-0tbWQYbfuGSRY_f4Gk_cggIA5qWBhuxiLn7kdw07dA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9mcmFt/ZXJ1c2VyY29udGVu/dC5jb20vaW1hZ2Vz/L0w4NXpSS0FpZ05k/ZWNpcFBzMGptYWYw/ZXRBTS5wbmc",
        img_alt: "facilitation certification from AJ&Smart",
        company: "AJ&Smart",
        desc: "How to Run In-Person & Remote Design Sprints Like a Pro",
        site: "https://go.ajsmart.com/masterclass",
        youtube: "",
        // skills: [1, 2, 3, 4, 5]
    },
    {
        active: false,
        cert_name: "ICP-IDO:  Implementing DevOps",
        subtitle: "DevOps & Agile",
        sub_url: "https://www.icagile.com/certification/implementing-devops",
        img: "https://images.credly.com/size/680x680/images/efc05654-77ea-4481-a937-4b5b9474e1f9/image.png",
        img_alt: "screenshot of GitHub repo with training materials",
        company: "ICAgile",
        desc: 'Verifies a professional’s ability to plan, build, monitor, and mature the CI/CD pipeline.',
        site: "https://www.credly.com/badges/3ddf7a37-ed39-4a77-93c7-c350bef315ca/linked_in_profile",
        youtube: "",
        // skills: [0, 6]
    },
    {
        active: false,
        cert_name: "ICP-FDO:  Foundations of DevOps",
        subtitle: "DevOps & Agile",
        sub_url: "https://www.icagile.com/certification/foundations-of-devops",
        img: "https://images.credly.com/size/680x680/images/ae1244d6-cce1-4826-b4d0-7c306231839b/image.png",
        img_alt: "screenshot of GitHub repo with training materials",
        company: "ICAgile",
        desc: "Demonstrates mindset change from traditional software development to agile delivery utilizing collaboration with the Operations team.",
        site: "https://www.credly.com/badges/af11ce73-557d-4594-94e5-01d63bdb729d/linked_in_profile",
        youtube: "",
        // skills: [0, 6]
    },
    {
        active: false,
        cert_name: "Systems Design",
        subtitle: "Cornell Certification",
        sub_url: "https://ecornell.cornell.edu/certificates/project-leadership-and-systems-design/systems-design/",
        img: "https://mycredentials.ecornell.cornell.edu/credential/image/ZCCzdfFluF",
        img_alt: "screenshot of certificate",
        company: "Cornell University",
        desc: "This program taught how to define the challenges to resolve, create functional requirements, and objectively measuring the value of any potential solution.",
        site: "https://mycredentials.ecornell.cornell.edu/credential/ZCCzdfFluF",
        youtube: "",
        // skills: [0, 6]
    },
]